version: '3'
services:
  music_summary_app:
    build: 
      context: .
    tty: true
    environment: 
      - NODE_ENV=development
    volumes: 
    - ./:/usr/src/app
    command: sh -c "cd music_summary && yarn start"
    ports: 
    - "3000:3000"